[package]
name = "leetcoderustapi"
version = "0.1.0"
edition = "2021"

[lib]
name = "leetcoderustapi"
path = "src/lib.rs"

[dependencies]
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.99"
tokio = { version = "1.29.1", features = ["full"] }